/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigTab: typeof import('./src/components/ConfigTab.vue')['default']
    ExamplesTab: typeof import('./src/components/ExamplesTab.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    PopupTab: typeof import('./src/components/PopupTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    ToolsTab: typeof import('./src/components/ToolsTab.vue')['default']
  }
}
