/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CustomIconDemo: typeof import('./src/components/features/CustomIconDemo.vue')['default']
    IconMdiApi: typeof import('~icons/mdi/api')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiDatabase: typeof import('~icons/mdi/database')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiFolder: typeof import('~icons/mdi/folder')['default']
    IconMdiInformation: typeof import('~icons/mdi/information')['default']
    IconMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IconMdiLightningBolt: typeof import('~icons/mdi/lightning-bolt')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMonitor: typeof import('~icons/mdi/monitor')['default']
    IconMdiPackageVariant: typeof import('~icons/mdi/package-variant')['default']
    IconMdiPalette: typeof import('~icons/mdi/palette')['default']
    IconMdiRocketLaunch: typeof import('~icons/mdi/rocket-launch')['default']
    IconMdiStarCircle: typeof import('~icons/mdi/star-circle')['default']
    IconMdiTools: typeof import('~icons/mdi/tools')['default']
    MainFooter: typeof import('./src/components/layout/MainFooter.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    Titlebar: typeof import('./src/components/layout/Titlebar.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
  }
}
