/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CustomIconDemo: typeof import('./src/components/features/CustomIconDemo.vue')['default']
    IconMaterialIconThemeRust: typeof import('~icons/material-icon-theme/rust')['default']
    IconMaterialIconThemeTauri: typeof import('~icons/material-icon-theme/tauri')['default']
    IconMaterialIconThemeVue: typeof import('~icons/material-icon-theme/vue')['default']
    IconMdiApi: typeof import('~icons/mdi/api')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiDatabase: typeof import('~icons/mdi/database')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiFolder: typeof import('~icons/mdi/folder')['default']
    IconMdiInformation: typeof import('~icons/mdi/information')['default']
    IconMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IconMdiLightningBolt: typeof import('~icons/mdi/lightning-bolt')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMonitor: typeof import('~icons/mdi/monitor')['default']
    IconMdiPackageVariant: typeof import('~icons/mdi/package-variant')['default']
    IconMdiPalette: typeof import('~icons/mdi/palette')['default']
    IconMdiRocketLaunch: typeof import('~icons/mdi/rocket-launch')['default']
    IconMdiStarCircle: typeof import('~icons/mdi/star-circle')['default']
    IconMdiStateMachine: typeof import('~icons/mdi/state-machine')['default']
    IconMdiTools: typeof import('~icons/mdi/tools')['default']
    IconProiconsApps: typeof import('~icons/proicons/apps')['default']
    IconProiconsArrowTrending: typeof import('~icons/proicons/arrow-trending')['default']
    IconProiconsBolt: typeof import('~icons/proicons/bolt')['default']
    IconProiconsBox: typeof import('~icons/proicons/box')['default']
    IconProiconsCode: typeof import('~icons/proicons/code')['default']
    IconProiconsColorPalette: typeof import('~icons/proicons/color-palette')['default']
    IconProiconsComputer: typeof import('~icons/proicons/computer')['default']
    IconProiconsDatabase: typeof import('~icons/proicons/database')['default']
    IconProiconsDelete: typeof import('~icons/proicons/delete')['default']
    IconProiconsFolder: typeof import('~icons/proicons/folder')['default']
    IconProiconsGraph: typeof import('~icons/proicons/graph')['default']
    IconProiconsHome: typeof import('~icons/proicons/home')['default']
    IconProiconsImage: typeof import('~icons/proicons/image')['default']
    IconProiconsInfo: typeof import('~icons/proicons/info')['default']
    IconProiconsPicture: typeof import('~icons/proicons/picture')['default']
    IconProiconsRocket: typeof import('~icons/proicons/rocket')['default']
    IconProiconsSettings: typeof import('~icons/proicons/settings')['default']
    IconProiconsSparkle: typeof import('~icons/proicons/sparkle')['default']
    IconProiconsSpinner: typeof import('~icons/proicons/spinner')['default']
    IconProiconsStar: typeof import('~icons/proicons/star')['default']
    IconProiconsToyBrick: typeof import('~icons/proicons/toy-brick')['default']
    IconProiconsWrench: typeof import('~icons/proicons/wrench')['default']
    MainFooter: typeof import('./src/components/layout/MainFooter.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Titlebar: typeof import('./src/components/layout/Titlebar.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
  }
}
